sudo: required
language: generic

services:
  - docker

script:
  - wget -O- https://raw.githubusercontent.com/harisvsulaiman/travis.debian.net/gh-pages/script.sh | sh -

branches:
  except:
    - /^debian\/\d/